name = "UnionArrays"
uuid = "d6dd79e4-993b-11e9-1366-0de1c9fe1122"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
