steps:
  - label: "Julia v1.5"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.5"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare("test/environments/cuda-jl15")'
      - julia -e 'using Run; Run.test(project="test/environments/cuda-jl15")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: |
      build.message !~ /^\[skip gpu\]/ &&
      build.message !~ /^\[skip cuda\]/
    timeout_in_minutes: 60

  - label: "Julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6-nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare("test/environments/cuda-jl16")'
      - julia -e 'using Run; Run.test(project="test/environments/cuda-jl16")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: |
      build.message !~ /^\[skip gpu\]/ &&
      build.message !~ /^\[skip cuda\]/
    timeout_in_minutes: 60
