name: Run test via Pkg.test()

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vanilla-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['~1.6.0-rc1', '1.0']
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
